stages:
  - build
  - deploy

build:linux:
  stage: build
  image: fedora:28
  before_script:
    - dnf install gcc git xz -y
    - export CHOOSENIM_NO_ANALYTICS=1
    - export CHOOSENIM_CHOOSE_VERSION="stable"
    - curl https://nim-lang.org/choosenim/init.sh -sSf > init.sh
    - sh init.sh -y
  script:
    - export PATH="$HOME/.nimble/bin:$PATH"
    - mkdir -p dist/
    - nimble build -d:release --passc:"-flto" -y
    - strip clr
    - tar cfJ dist/clr-linux-x86_64.tar.xz clr
  artifacts:
    expire_in: 30 days
    paths:
      - dist/

deploy:linux:
  stage: deploy
  image: fedora:28
  dependencies:
    - build:linux
  only:
    - tags
  before_script:
    - dnf install golang -y
    - go get github.com/itchio/gothub
  script:
    - export PATH="$HOME/go/bin:$PATH"
    - gothub release
      --user Calinou
      --repo clr
      --tag "$CI_COMMIT_TAG"
    - gothub upload
      --user Calinou
      --repo clr
      --tag "$CI_COMMIT_TAG"
      --name "clr-$CI_COMMIT_TAG-linux-x86_64.tar.xz"
      --file "dist/clr-linux-x86_64.tar.xz"
